export const data = [
    {
        id: 1,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 2,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 3,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 4,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 5,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 6,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 7,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 8,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 9,
        rockColor: "blackRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 10,
        rockColor: "blackRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 11,
        rockColor: "blackRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 12,
        rockColor: "blackRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 13,
        rockColor: "blackRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 14,
        rockColor: "blackRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 15,
        rockColor: "blackRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 16,
        rockColor: "blackRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 17,
        rockColor: "blackRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 18,
        rockColor: "blackRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 19,
        rockColor: "blackRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 20,
        rockColor: "blackRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 21,
        rockColor: "blackRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 22,
        rockColor: "blackRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 23,
        rockColor: "blackRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 24,
        rockColor: "blackRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 25,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 26,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 27,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 28,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 29,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 30,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 31,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 32,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 33,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 34,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 35,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 36,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 37,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 38,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 39,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 40,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 41,
        rockColor: "whiteRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 42,
        rockColor: "whiteRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 43,
        rockColor: "whiteRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 44,
        rockColor: "whiteRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 45,
        rockColor: "whiteRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 46,
        rockColor: "whiteRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 47,
        rockColor: "whiteRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 48,
        rockColor: "whiteRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 49,
        rockColor: "whiteRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 50,
        rockColor: "whiteRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 51,
        rockColor: "whiteRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 52,
        rockColor: "whiteRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 53,
        rockColor: "whiteRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 54,
        rockColor: "whiteRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 55,
        rockColor: "whiteRock.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 56,
        rockColor: "whiteRock.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 57,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 58,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 59,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 60,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 61,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 62,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }, {
        id: 63,
        rockColor: "empty.png",
        backgroundColor: "#b77b59",
        isCheck: false
    }, {
        id: 64,
        rockColor: "empty.png",
        backgroundColor: "white",
        isCheck: false
    }

]